## Name : Fawzi abdelnaby elsayed
## Group : One(Mansoura)
## Assignment_2_Day_1

## Multi-layer perceptron(with one input layer, one hidden layer and one output layer)


In [2]:
# Import required libraries :
import numpy as np
# Define input features :
input_features = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
print (input_features.shape)
print (input_features)
# Define target output :
target_output = np.array([[0,1,1,1]])
# Reshaping our target output into vector :
target_output = target_output.reshape(4,1)
print(target_output.shape)
print (target_output)
# Define weights :
# 6 for hidden layer
# 3 for output layer
# 9 total
weight_hidden= np.array([[0.1,0.2,0.3],
                         [0.4,0.5,0.6],
                         [0.01,0.02,0.03]])

weight_output = np.array([[0.7],[0.8],[0.9]])
# Learning Rate :
lr = 0.05
# Sigmoid function :
def sigmoid(x):
    return 1/(1+np.exp(-x))
# Derivative of sigmoid function :
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

for epoch in range(100):
 # Input for hidden layer :
    input_hidden = np.dot(input_features, weight_hidden)
 
 # Output from hidden layer :
    output_hidden = sigmoid(input_hidden)
 
 # Input for output layer :
    input_op = np.dot(output_hidden, weight_output)
 
 # Output from output layer :
    output_op = sigmoid(input_op)
    #==========================================================
 # Phase1
 
 # Calculating Mean Squared Error :
    error_out = ((1 / 2) * (np.power((output_op - target_output), 2)))
    print(error_out.sum())
 
 # Derivatives for phase 1 :
    derror_douto = output_op - target_output
    douto_dino = sigmoid_der(input_op) 
    dino_dwo= output_hidden
    derror_dwo = output_hiddenderror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)
    #===========================================================
 # Phase 2 
 # derror_w1 = derror_douth * douth_dinh * dinh_dw1
 # derror_douth = derror_dino * dino_outh
 
 # Derivatives for phase 2 :
    derror_dino = derror_douto * douto_dino
    dino_douth = weight_output
    derror_douth = np.dot(derror_dino , dino_douth.T)
    douth_dinh = sigmoid_der(input_hidden) 
    dinh_dwh = input_features
    derror_wh = np.dot(dinh_dwh.T, douth_dinh * derror_douth)# Update Weights
    weight_hidden -= lr * derror_wh
    weight_output -= lr * derror_dwo
 
 # Final hidden layer weight values :
print (weight_hidden)
print('###################################################################')
# Final output layer weight values :
print (weight_output)


(4, 3)
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
(4, 1)
[[0]
 [1]
 [1]
 [1]]
0.3486706058151145
0.3485737115950348
0.3484773975900103
0.3483816588533338
0.3482864904506809
0.3481918874607367
0.34809784497580876
0.34800435810242514
0.3479114219619205
0.34781903169100564
0.3477271824423263
0.3476358693850062
0.3475450877051769
0.34745483260649523
0.3473650993106463
0.34727588305783336
0.3471871791072551
0.3470989827375693
0.3470112892473437
0.34692409395549434
0.34683739220171045
0.3467511793468674
0.3466654507734271
0.34658020188582545
0.3464954281108487
0.3464111248979963
0.34632728771983234
0.34624391207232597
0.34616099347517854
0.3460785274721408
0.345996509631317
0.3459149355454589
0.3458338008322486
0.34575310113456886
0.34567283212076527
0.345592989484894
0.3455135689469631
0.34543456625315977
0.34535597717606914
0.3452777975148827
0.345200023095597
0.3451226497712009
0.3450456734218552
0.3449690899550617
0.34489289530582246
0.34481708543679074
0.3447416563384118
0.3446666040290558
0.